### ISSUE TITLE
Attribute UI: Handle MAP type

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/huey#182]
Currently we do not have an icon for MAP, 
Also we don't properly expand MAP:

![image](https://github.com/user-attachments/assets/2d8cf022-7465-479a-b656-e203c9cb2554)

(sample file BWActivityMarch2024.json not shared here)

**Comment by rpbouman** [comment]
Unnesting has issue determining the type:

![image](https://github.com/user-attachments/assets/68a44de6-72f6-4732-9ce8-05c85558bc58)

```
SQLHelper.js:1113 Uncaught (in promise) Error: Type "MAP(VARCHAR, VARCHAR)[]" is not a STRUCT: expected keyword STRUCT at position 0
    at getStructTypeDescriptor (SQLHelper.js:1113:11)
    at getMemberExpressionType (SQLHelper.js:1193:26)
    at QueryAxisItem.getQueryAxisItemDataType (QueryModel.js:220:18)
    at QueryAxisItem.createFormatter (QueryModel.js:4:34)
    at #axisButtonClicked (AttributeUi.js:507:35)
    at AttributeUi.<anonymous> (AttributeUi.js:459:32)
```

**Comment by rpbouman** [comment]
We should treat MAP as a special type, and give it special derivations (like we do for array).

This looks like the thing we should be able to do:

```
with cte1 as (
  SELECT unnest("__huey_data_foundation"."records")  AS "records"
  ,      generate_subscripts("__huey_data_foundation"."records", 1)  AS "id"
  FROM read_json_auto( 'C:\roland\projects\QuaQuery\files\BWActivityMarch2024.json' ) AS "__huey_data_foundation"
),
cte2 as (
  SELECT id
  ,      unnest(map_keys(records)) as key
  ,      unnest(map_values(records)) as value
  FROM cte1
)
select *
from cte2
```

(first cte unwraps the array MAP(VARCHAR, VARCHAR)[], second cte unwraps the keys and values)

So the derivations 
- unnest(map_keys(records)) 
- unnest(map_values(records)) 
should be treated as same unnesting stage, just like unnest and generate subscripts are.

In fact, it makes sense to give MAP type 3 such derivations: one for the keys, second for the values, third for the subscripts of the elements in the keys/values lists.

**Comment by rpbouman** [comment]
These look useful

[map_entries(map)](https://duckdb.org/docs/sql/functions/map.html#map_entriesmap)
[cardinality(map)](https://duckdb.org/docs/sql/functions/map.html#cardinalitymap)
