### ISSUE TITLE
ExportUi: export to clipboard may fail when browser devtools is open, or more generally when the document is not focuesed

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/huey#305]
![image](https://github.com/user-attachments/assets/c18db98a-bc68-489f-839a-7c23ee0d948e)

```
NotAllowedError: Failed to execute 'write' on 'Clipboard': Document is not focused.
    at copyToClipboard (file:///C:/roland/projects/huey/src/util/clipboard/clipboard.js:22:17)
    at ExportUi.exportData (file:///C:/roland/projects/huey/src/ExportUi/ExportDialog.js:268:17)
    at async #executeExport (file:///C:/roland/projects/huey/src/ExportUi/ExportDialog.js:462:7)
```

This is a browser limitation and a minor nuisance. However it does make it harder to troubleshoot. Would be cool if we could catch this and perhaps focus the document and retry.

**Comment by rpbouman** [comment]
It appears that firefox is not affected.
