### ISSUE TITLE
FilterUi: picklist query doesn't work for nested items

### ISSUE THREAD

**Issue by rpbouman** [rpbouman/huey#315]
![image](https://github.com/user-attachments/assets/0e0abb74-6e78-4e6b-84e6-e771b242d0f4)

To be precise, this is with unnested map keys

```
Uncaught (in promise) Error: Type "MAP(VARCHAR, VARCHAR)[]" is not a STRUCT: expected keyword STRUCT at position 0
    at getStructTypeDescriptor (SQLHelper.js:1176:11)
    at getMemberExpressionType (SQLHelper.js:1326:34)
    at QueryAxisItem.getQueryAxisItemDataType (QueryModel.js:269:18)
    at QueryAxisItem.getFilterConditionSql (QueryModel.js:404:40)
    at SqlQueryGenerator.js:122:28
    at Array.map (<anonymous>)
    at #getConditionForFilterItems (SqlQueryGenerator.js:121:6)
    at #generateWhereClause (SqlQueryGenerator.js:609:73)
    at #getSqlSelectStatementForFinalStage (SqlQueryGenerator.js:545:43)
    at SqlQueryGenerator.getSqlSelectStatementForAxisItems (SqlQueryGenerator.js:636:68)
```

**Comment by rpbouman** [comment]
On gitub events, on an unnested array we get:
```
SQLHelper.js:1175 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at getStructTypeDescriptor (SQLHelper.js:1175:25)
    at getMemberExpressionType (SQLHelper.js:1326:34)
    at getMemberExpressionType (SQLHelper.js:1329:16)
    at QueryAxisItem.getQueryAxisItemDataType (QueryModel.js:269:18)
    at QueryAxisItem.getFilterConditionSql (QueryModel.js:404:40)
    at SqlQueryGenerator.js:122:28
    at Array.map (<anonymous>)
    at #getConditionForFilterItems (SqlQueryGenerator.js:121:6)
    at #generateWhereClause (SqlQueryGenerator.js:609:73)
    at #getSqlSelectStatementForFinalStage (SqlQueryGenerator.js:545:43)
```
![image](https://github.com/user-attachments/assets/2afc84e6-eddd-4d89-b208-e3600a9bc00a)
